services:
  firefox:
    build: .
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
    volumes:
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
